### ISSUE TITLE
Une petite aide pour l'installation

### ISSUE THREAD

**Issue by SteamWind** [RasCarlito/moment-locale-fr#1]
Hello,
Une petite aide pour l'installation et l'utilisation serait très appréciée. 👍

**Comment by ghost** [comment]
Hello @SteamWind :)

C'est vrai que j'aurais dû faire une doc. Mais en fait ce projet n'est pas vraiment nécessaire pour traduire moment.
La traduction est déjà intégrée https://github.com/moment/moment/blob/develop/locale/fr.js

Il suffit d'appeler `moment.locale('fr')` pour la faire fonctionner.

Dans ma version j'ai juste modifié la traduction `"un an"` par `"une année"` [ici](https://github.com/RasCarlito/moment-locale-fr/blob/master/fr.js#L46) pour des raisons fonctionnelles.

Si tu veux tout de même utiliser ma version de la traduction il te suffit de le require/import après moment
En général je me créer un fichier "utils/moment.js" par exemple
```js
import moment from 'moment'
import fr from 'moment-locale-fr'

moment.locale('fr')

export default moment
```

Ensuite il te suffit d'import ce fichier à la place de moment `import moment from 'utils/moment'`

J'espère que ça t'aidera un peu, et j'écrirais une doc à l'occasion :)

Cheers

**Comment by SteamWind** [comment]
J'avais pas vu la traduction intégrée en effet, merci pour l'info du coup.
Je crois que tu peux sinon faire un fichier de traduction hérité ou tu récupère le locale de base et tu modifie quelques propriétés (comme dans ton cas) comme expliqué dans la doc: http://momentjs.com/docs/#/customization/

**Comment by ghost** [comment]
Pas bête ! :smile:
